### PR TITLE
Use consistent notation for complexity annotation

### LINKED ISSUE #722: Mysterious complexity annotations for `compose`
Here's an example from `Data.Map.Lazy`:

image

When I first saw this, I was a bit mystified.

* Does `ab` mean `a * b`?
* Does `|ab|` mean something like `abs(ab)`?

I now suspect that `|ab|` is supposed to be the size of the `(Map a b)` argument, but that took me a while.

Other functions nearby generally use `m` and `n` for the sizes of their arguments. Arguably that could be made clearer too. Nevertheless I think consistency with the surrounding code might be clearer than this kind of exceptional convention.

@alexfmpe Thoughts?

### PR DESCRIPTION
**Pull request by alexfmpe**
Fix #722

### CODE REVIEW

File: containers/src/Data/IntMap/Internal.hs [hunk 1]
```diff
@@ -771,10 +771,12 @@ disjoint t1@(Bin p1 m1 l1 r1) t2@(Bin p2 m2 l2 r2)
 {--------------------------------------------------------------------
   Compose
 --------------------------------------------------------------------}
--- | /O(|ab|*min(|bc|,W))/. Relate the keys of one map to the values of
+-- Relate the keys of one map to the values of
```
Comment (sjakobi) [inline containers/src/Data/IntMap/Internal.hs:774]: Right now, this is not a haddock comment:

```suggestion
-- | Relate the keys of one map to the values of
```

File: containers/src/Data/IntMap/Internal.hs [hunk 2]
```diff
@@ -771,10 +771,12 @@ disjoint t1@(Bin p1 m1 l1 r1) t2@(Bin p2 m2 l2 r2)
...
 -- the other, by using the values of the former as keys for lookups
 -- in the latter.
 --
+-- O (n * log m), where m is the size of the first argument
```
Comment (sjakobi) [inline containers/src/Data/IntMap/Internal.hs:778]: I wonder whether this might look even nicer.

```suggestion
-- Complexity: /O(n * log m)/, where /m/ is the size of the first argument
```

Could you possibly share a screenshot of the rendered final result?

**Comment by treeowl** [comment]
One of these modules somewhere uses MathJax. Let's make them all do that.

**Comment by sjakobi** [comment]
> One of these modules somewhere uses MathJax. Let's make them all do that.

@treeowl Could you clarify what you mean here?

FWIW, what I was looking for in this PR was a proper fix for #722. Any other possible haddock improvements don't need to happen in this PR IMHO.

File: containers/src/Data/IntMap/Internal.hs (hunk 2 above)
Comment (alexfmpe) [reply containers/src/Data/IntMap/Internal.hs]: intmap
map

**Comment by treeowl** [comment]
> > One of these modules somewhere uses MathJax. Let's make them all do that.
> 
> @treeowl Could you clarify what you mean here?

Look how all the math is formatted in `Data.Sequence`. Let's do that everywhere.

**Comment by sjakobi** [comment]
> Look how all the math is formatted in `Data.Sequence`. Let's do that everywhere.

Oh yeah. That _does_ look nicer! I'd argue that this is a different issue than what this PR was about though.

File: containers/src/Data/IntMap/Internal.hs [hunk 3]
```diff
@@ -771,10 +771,12 @@ disjoint t1@(Bin p1 m1 l1 r1) t2@(Bin p2 m2 l2 r2)
 {--------------------------------------------------------------------
   Compose
 --------------------------------------------------------------------}
--- | /O(|ab|*min(|bc|,W))/. Relate the keys of one map to the values of
+-- | Relate the keys of one map to the values of
 -- the other, by using the values of the former as keys for lookups
 -- in the latter.
 --
+-- Complexity: /O(|n|*min(|m|,W))/, where /m/ is the size of the first argument
```
Comment (sjakobi) [inline containers/src/Data/IntMap/Internal.hs:778]:
```suggestion
-- Complexity: /O(n*min(m,W))/, where /m/ is the size of the first argument
```

File: containers/src/Data/IntMap/Strict/Internal.hs [hunk 4]
```diff
@@ -721,10 +721,12 @@ intersectionWithKey f m1 m2
 {--------------------------------------------------------------------
   Compose
 --------------------------------------------------------------------}
--- | /O(|ab|*min(|bc|,W))/. Relate the keys of one map to the values of
+-- | Relate the keys of one map to the values of
 -- the other, by using the values of the former as keys for lookups
 -- in the latter.
 --
+-- Complexity: /O(|n|*min(|m|,W))/, where /m/ is the size of the first argument
```
Comment (sjakobi) [inline containers/src/Data/IntMap/Strict/Internal.hs:728]:
```suggestion
-- Complexity: /O(n*min(m,W))/, where /m/ is the size of the first argument
```

Comment (alexfmpe) [reply containers/src/Data/IntMap/Strict/Internal.hs:728]: oops

**Comment by alexfmpe** [comment]
> Look how all the math is formatted in Data.Sequence. Let's do that everywhere.

If that's the convention going forward, I might as well make _these_ particular annotations conform to it now

**Comment by sjakobi** [comment]
> > Look how all the math is formatted in Data.Sequence. Let's do that everywhere.
> 
> If that's the convention going forward, I might as well make _these_ particular annotations conform to it now

I wouldn't mind. I don't currently volunteer to update the remaining annotations though.

**Comment by sjakobi** [comment]
Could you share another screenshot, @alexfmpe. I think you're somehow using fewer backslashes than the annotations in `Data.Sequence` tend to have.

Here are the docs BTW: https://haskell-haddock.readthedocs.io/en/latest/markup.html#mathematics-latex

**Comment by alexfmpe** [comment]
Good catch, the `log`/`min` functions were being rendered as variables

**Comment by alexfmpe** [comment]
intmap
map

**Comment by sjakobi** [comment]
I've made https://github.com/haskell/containers/issues/731 where we can track the remaining annotations to convert.

**Comment by treeowl** [comment]
Why did the complexity info move?

**Comment by sjakobi** [comment]
> Why did the complexity info move?

That was my idea. It's much longer now, so it would have distracted from the function description if we had kept it in the old spot.

**Comment by treeowl** [comment]
We need a good and consistent approach to that. As I recall, @m-renaud wants it always at the bottom. I'm skeptical about that, because the complexity of an operation seems like one of the most important things to know about it. But it's also true that a long complexity statement before the basic info about what an operation does is problematic. So I dunno.

**Comment by sjakobi** [comment]
Putting it consistently at the bottom (above the `since`-annotation?) sounds fine to me.

A closed PR doesn't seem like a good place to discuss this further though. Consider opening an issue?

**Comment by m-renaud** [comment]
I was actually thinking about this the other day, we have the `@since` metadata which has a consistent rendering across packages, could we introduce standard `@complexity` and `@complexityInfo` annotations and do something similar. Agreed that this is probably not the best place to discuss though.
