### PR TITLE
Fix IntSet and IntMap validity tests (resolves #522).

### LINKED ISSUE #522: IntSetValidity: commonPrefix too loose
This code:
```
-- Invariant: Prefix is the common high-order bits that all elements share to
--            the left of the Mask bit.
commonPrefix :: IntSet -> Bool
commonPrefix t =
  case t of
    Nil -> True
    Tip _ _ -> True
    b@(Bin p _ _ _) -> all (sharedPrefix p) (elems b)
  where
    sharedPrefix :: Prefix -> Int -> Bool
    sharedPrefix p a = 0 == (p `xor` (p .&. a))
```
is too weak, I believe: It checks only that the outermost prefix is correct, but not of the `Bin`’s inside the left and right tree.

Maybe 
```
-- Invariant: Prefix is the common high-order bits that all elements share to
--            the left of the Mask bit.
commonPrefix :: IntSet -> Bool
commonPrefix t =
  case t of
    Nil -> True
    Tip _ _ -> True
    b@(Bin p _ l r) -> all (sharedPrefix p) (elems b) && commonPrefix l && commonPrefix r
  where
    sharedPrefix :: Prefix -> Int -> Bool
    sharedPrefix p a = 0 == (p `xor` (p .&. a))
```
would be better?

### PR DESCRIPTION
**Pull request by m-renaud**
The previous implementations only checked the `commonPrefix` and `maskRespected`
invariant for the top level Bin constructor and didn't appropriately recurse
into subtrees.

This resolves #522.

### CODE REVIEW

File: tests/IntMapValidity.hs [hunk 1]
```diff
@@ -60,4 +60,6 @@ maskRespected t =
     Tip _ _ -> True
     Bin _ binMask l r ->
       all (\x -> zero x binMask) (keys l) &&
-      all (\x -> not (zero x binMask)) (keys r)
+      all (\x -> not (zero x binMask)) (keys r) &&
+      maskRespected l &&
+      maskRespected r
```
Comment (treeowl) [inline tests/IntMapValidity.hs]: This implementation of `maskRespected` is at least quadratic. Can't you get it down to linear?

**Comment by m-renaud** [comment]
I had considered doing that but since this is test only code and I didn't
see any noticable slowdown when running the tests I wasn't sure it was
worth the complication. It may make it less obvious what is being tested if
it's optimized as well. If you'd still like me to optimize it let me know.

**Comment by treeowl** [comment]
You're right that getting `O(n)` will be too complicated/too far removed from the basic operations. But I think a small `O(W*n)` should be pretty reasonable. Does this look right?

```haskell
 maskRespected :: IntMap a -> Bool
 maskRespected = go [] [] where
   go should_zero shouldnt_zero t =
     case t of
       Nil -> True
       Tip k _ -> all (zero k) should_zero && all (not . zero k) shouldnt_zero
       Bin _ binMask l r ->
         go (binMask : should_zero) shouldnt_zero l &&
         go should_zero (binMask : shouldnt_zero) r
```

**Comment by treeowl** [comment]
Actually, I may have been wrong about your version being quadratic....

**Comment by treeowl** [comment]
Yeah, your version is probably not actually as bad as I thought. Sorry.

**Comment by m-renaud** [comment]
No worries, the version you posted is more efficient but not immediately obvious (to me at least) that it's testing the correct thing.

File: tests/IntMapValidity.hs (hunk 1 above)
Comment (m-renaud) [reply tests/IntMapValidity.hs]: That's something we could do, but I'm not sure if it would improve or hurt the readability. It would require fewer traversals of the tree but may make it more difficult to see how each invariant is tested.
