### PR TITLE
More efficient Eq, Ord for Set, Map

### LINKED ISSUE #1016: Faster Eq and Ord
The following operations are implemented by converting to lists and comparing.

- [x] Set `==` (improved in #1017)
- [x] Set `compare` (same as above)
- [x] Map `==` (same as above)
- [x] Map `compare` (same as above)
- [x] IntSet `compare` (#1086)
- [x] IntMap `compare` (same as above)
- [x] Seq `==` (#1035)
- [x] Seq `compare` (same as above)

This is not the best we can do for a couple of reasons:

1. No specialization. `Eq` and `Ord` for lists don't specialize (but there a few manually specified exceptions).
2. No list fusion. We materialize both lists.

See list instances [Eq](https://gitlab.haskell.org/ghc/ghc/-/blob/cf47b96f8b8100d9f9ad1b8121cbfb65fd7eaf2a/libraries/ghc-prim/GHC/Classes.hs#L261-267), [Ord](https://gitlab.haskell.org/ghc/ghc/-/blob/cf47b96f8b8100d9f9ad1b8121cbfb65fd7eaf2a/libraries/ghc-prim/GHC/Classes.hs#L482-491).

---

I tried a couple of alternatives and saw decent improvements

```
  Set Word
    compare: OK
      3.03 ms ± 189 μs,  11 MB allocated, 1.8 MB copied,  23 MB peak memory
    setCmp:  OK
      1.64 ms ± 143 μs, 8.4 MB allocated, 583 KB copied,  23 MB peak memory, 0.54x
    setCmp2: OK
      947  μs ±  68 μs, 5.3 MB allocated, 795 B  copied,  23 MB peak memory, 0.31x
```

```hs
-- Current version but fused with the first set
setCmp :: Ord a => Set a -> Set a -> Ordering
setCmp xs ys0 = S.foldr f z xs (S.toList ys0)
  where
    f x k = oneShot $ \ys -> case ys of
      [] -> GT
      y:ys' -> compare x y <> k ys'
    z ys = case ys of
      [] -> EQ
      _ -> LT
{-# INLINABLE setCmp #-}
```

```hs
-- Somewhat like a traverse with StateT [a] (Either Bool)
setCmp2 :: Ord a => Set a -> Set a -> Ordering
setCmp2 xs ys0 = case go xs (S.toList ys0) of
  WithO o ys' ->
    o <> case ys' of
      [] -> EQ
      _ -> LT
  where
    go Tip ys = WithO EQ ys
    go (Bin _ x l r) ys = go l ys >>- f >>- go r
      where
        f [] = WithO GT []
        f (y:ys') = WithO (compare x y) ys'
    ox@(WithO o x) >>- f = case o of
      EQ -> f x
      _ -> ox
{-# INLINABLE setCmp2 #-}

data WithO a = WithO !Ordering a
```

<details>
<summary>Benchmark code</summary>

```hs
import Test.Tasty.Bench
import qualified Data.Set as S
import Data.Set.Internal (Set(..))
import GHC.Exts (oneShot)

main :: IO ()
main = defaultMain
  [ env (pure (S.fromList xs_)) $ \xs -> bgroup "Set Word"
    [ bench "eq" $ whnf (\ys -> ys == ys) xs
    , bench "compare" $ whnf (\ys -> compare ys ys) xs
    , bcompare "$0 == \"All.Set.eq\"" $ bench "eq new" $ whnf (\ys -> setEq ys ys) xs
    , bcompare "$0 == \"All.Set.compare\"" $ bench "setCmp" $ whnf (\ys -> setCmp ys ys) xs
    , bcompare "$0 == \"All.Set.compare\"" $ bench "setCmp2" $ whnf (\ys -> setCmp2 ys ys) xs
    ]
  ]
  where
    xs_ = [1..100000] :: [Word]

setEq :: Eq a => Set a -> Set a -> Bool
setEq xs ys0 = S.foldr f z xs (S.toList ys0)
  where
    f x k = oneShot $ \ys -> case ys of
      [] -> False
      y:ys' -> x == y && k ys'
    z ys = case ys of
      [] -> True
      _ -> False

-- Current version but fused with the first set
setCmp :: Ord a => Set a -> Set a -> Ordering
setCmp xs ys0 = S.foldr f z xs (S.toList ys0)
  where
    f x k = oneShot $ \ys -> case ys of
      [] -> GT
      y:ys' -> compare x y <> k ys'
    z ys = case ys of
      [] -> EQ
      _ -> LT

-- Somewhat like a traverse with StateT [a] (Either Bool)
setCmp2 :: Ord a => Set a -> Set a -> Ordering
setCmp2 xs ys0 = case go xs (S.toList ys0) of
  WithO o ys' ->
    o <> case ys' of
      [] -> EQ
      _ -> LT
  where
    go Tip ys = WithO EQ ys
    go (Bin _ x l r) ys = go l ys >>- f >>- go r
      where
        f [] = WithO GT []
        f (y:ys') = WithO (compare x y) ys'
    ox@(WithO o x) >>- f = case o of
      EQ -> f x
      _ -> ox

data WithO a = WithO !Ordering a
```

</details>

---

For now, converting the second set to a list is not avoided.

* For IntSet and IntMap it could be avoided by utilizing the natural structure (#470, #787). That implementation will likely be quite different from the above style.
* For Set and Map it could be avoided by implementing an "iterator" on the tree with a stack, but I'm not sure if this will be much better. I will try this out later.

### PR DESCRIPTION
**Pull request by meooow25**
More efficient implementation moving away from the `toList` based approach.

For #1016.

---

Benchmarks, on GHC 9.6.3:

```
Set before:
  eq:      OK
    74.9 μs ± 5.6 μs, 447 KB allocated,  86 B  copied, 7.0 MB peak memory
  compare: OK
    61.9 μs ± 5.9 μs, 447 KB allocated,  85 B  copied, 7.0 MB peak memory

Set after:
  eq:      OK
    29.2 μs ± 2.7 μs, 128 KB allocated,  11 B  copied, 7.0 MB peak memory, 61% less than baseline
  compare: OK
    29.1 μs ± 2.8 μs, 128 KB allocated,  11 B  copied, 7.0 MB peak memory, 53% less than baseline

Map before:
  eq:      OK
    123  μs ±  11 μs, 637 KB allocated, 163 B  copied, 9.0 MB peak memory
  compare: OK
    168  μs ±  15 μs, 637 KB allocated, 163 B  copied, 9.0 MB peak memory

Map after:
  eq:      OK
    38.5 μs ± 3.6 μs, 159 KB allocated,  15 B  copied, 9.0 MB peak memory, 68% less than baseline
  compare: OK
    39.1 μs ± 3.4 μs, 159 KB allocated,  15 B  copied, 9.0 MB peak memory, 76% less than baseline
```

Note: Why is the improvement less for `Set`? This is because the benchmarks use `Set Int`, and there happen to be specializations for `Eq [Int]` and `Ord [Int]`. Without specializations, the improvement for `Set` is (70-75%) just like `Map` (see numbers in #1016).

### CODE REVIEW

**Comment by meooow25** [comment]
For the record, if we have

```hs
foo :: Set Int -> Set Int ->Ordering
foo = compare
```

(with GHC 9.6.3) it gets compiled to the Core

<details>

```hs
Rec {
-- RHS size: {terms: 101, types: 97, coercions: 33, joins: 0/0}
$wgo1 [InlPrag=[2], Occ=LoopBreaker]
  :: Set Int -> Iterator Int -> (# Ordering, Iterator Int #)
[GblId[StrictWorker([!, !])],
 Arity=2,
 Str=<1L><1L>,
 Unf=OtherCon []]
$wgo1
  = \ (ds_s5eh :: Set Int) (eta_s5ei :: Iterator Int) ->
      case ds_s5eh of {
        Bin bx_a3pH k_a3pI ds1_a3pJ ds2_a3pK ->
          case k_a3pI of { I# x#_s5zS ->
          case bx_a3pH of {
            __DEFAULT ->
              case $wgo1 ds1_a3pJ eta_s5ei of wild2_X1E
              { (# ww_s5vE, ww1_s5vF #) ->
              case ww_s5vE of {
                __DEFAULT -> wild2_X1E;
                EQ ->
                  case ww1_s5vF `cast` <Co:2> :: ... of {
                    Push x1_a3qi r1_a3qj stk'_a3qk ->
                      case x1_a3qi of { I# y#_s5zV ->
                      case iterDown @Int r1_a3qj stk'_a3qk of nt_a3qm { __DEFAULT ->
                      case <# x#_s5zS y#_s5zV of {
                        __DEFAULT ->
                          case ==# x#_s5zS y#_s5zV of {
                            __DEFAULT -> (# GT, nt_a3qm `cast` <Co:3> :: ... #);
                            1# -> $wgo1 ds2_a3pK (nt_a3qm `cast` <Co:3> :: ...)
                          };
                        1# -> (# LT, nt_a3qm `cast` <Co:3> :: ... #)
                      }
                      }
                      };
                    Nada -> (# GT, (Nada @Int) `cast` <Co:3> :: ... #)
                  }
              }
              };
            1# ->
              case eta_s5ei `cast` <Co:2> :: ... of {
                Push x_a3qr r1_a3qs stk'_a3qt ->
                  case x_a3qr of { I# y#_s5A1 ->
                  case iterDown @Int r1_a3qs stk'_a3qt of nt_a3qv { __DEFAULT ->
                  case <# x#_s5zS y#_s5A1 of {
                    __DEFAULT ->
                      case ==# x#_s5zS y#_s5A1 of {
                        __DEFAULT -> (# GT, nt_a3qv `cast` <Co:3> :: ... #);
                        1# -> (# EQ, nt_a3qv `cast` <Co:3> :: ... #)
                      };
                    1# -> (# LT, nt_a3qv `cast` <Co:3> :: ... #)
                  }
                  }
                  };
                Nada -> (# GT, (Nada @Int) `cast` <Co:3> :: ... #)
              }
          }
          };
        Tip ->
          case eta_s5ei `cast` <Co:2> :: ... of nt_s54V { __DEFAULT ->
          (# EQ, nt_s54V `cast` <Co:3> :: ... #)
          }
      }
end Rec }

-- RHS size: {terms: 20, types: 23, coercions: 5, joins: 0/0}
foo [InlPrag=INLINABLE] :: Set Int -> Set Int -> Ordering
[GblId,
 Arity=2,
 Str=<1L><1L>,
 Unf=Unf{Src=<vanilla>, TopLvl=True,
         Value=True, ConLike=True, WorkFree=True, Expandable=True,
         Guidance=IF_ARGS [0 0] 110 20}]
foo
  = \ (s1_a3oU :: Set Int) (s2_a3oV :: Set Int) ->
      case $wgo1
             s1_a3oU ((iterDown @Int s2_a3oV (Nada @Int)) `cast` <Co:3> :: ...)
      of
      { (# ww_s5vE, ww1_s5vF #) ->
      case ww_s5vE of wild1_a3qC {
        __DEFAULT -> wild1_a3qC;
        EQ ->
          case ww1_s5vF `cast` <Co:2> :: ... of {
            Push ds_a4A6 ds1_a4A7 ds2_a4A8 -> LT;
            Nada -> EQ
          }
      }
      }
```

</details>

Which looks pretty good to me!

**Comment by meooow25** [comment]
@treeowl, would appreciate a review if you have the time for it.

File: containers/src/Data/Map/Internal.hs [hunk 1]
```diff
@@ -4118,6 +4119,30 @@ deleteFindMax t = case maxViewWithKey t of
   Nothing -> (error "Map.deleteFindMax: can not return the maximal element of an empty map", Tip)
   Just res -> res
 
+{--------------------------------------------------------------------
+  Iterator
+--------------------------------------------------------------------}
+
+newtype Iterator k a = Iterator (Stack k a)
```
Comment (treeowl) [inline containers/src/Data/Map/Internal.hs:4128]: As far as I can tell, this `newtype` just introduces noise and makes it less obvious what's being passed around. Why not just use `Stack` directly? If we were using linear types, I could imagine that as a useful public API, but I'm not sure it makes sense in the current context.

File: containers/src/Data/Map/Internal.hs [hunk 2]
```diff
@@ -4118,6 +4119,30 @@ deleteFindMax t = case maxViewWithKey t of
...
+
+iterDown :: Map k a -> Stack k a -> Stack k a
+iterDown Tip stk = stk
+iterDown (Bin _ kx x l r) stk = iterDown l (Push kx x r stk)
```
Comment (treeowl) [inline containers/src/Data/Map/Internal.hs:4132]: Please document all these functions individually. A good abstraction deserves a good documentation.

File: containers/src/Data/Map/Internal.hs (hunk 1 above)
Comment (meooow25) [reply containers/src/Data/Map/Internal.hs:4128]: I can change it to just use `Stack`, don't have a strong opinion on it.

I'm not sure what you mean about linear types though. We could expose this in the public API as it is, if we wanted to.

File: containers/src/Data/Map/Internal.hs [hunk 3]
```diff
@@ -4118,6 +4119,30 @@ deleteFindMax t = case maxViewWithKey t of
...
+
+iterator :: Map k a -> Iterator k a
+iterator m = Iterator (iterDown m Nada)
+
+iterNext :: Iterator k a -> Maybe (StrictPair (k, a) (Iterator k a))
+iterNext (Iterator stk) = case stk of
+  Nada -> Nothing
+  Push kx x r stk' -> Just $! (kx, x) :*: Iterator (iterDown r stk')
+{-# INLINE iterNext #-}
```
Comment (treeowl) [inline containers/src/Data/Map/Internal.hs:4141]: Do the strict pairs go away? Do the inner pairs? Does GHC hang on to the fact that the keys are in WHNF?

File: containers/src/Data/Map/Internal.hs (hunk 1 above)
Comment (treeowl) [reply containers/src/Data/Map/Internal.hs:4128]: Oh, I meant if we wanted to leave open the option of representing it with a mutable array without a state thread type parameter.

Comment (meooow25) [reply containers/src/Data/Map/Internal.hs]: Ah I see. Well, removed the newtype for now.

File: containers/src/Data/Map/Internal.hs (hunk 3 above)
Comment (meooow25) [reply containers/src/Data/Map/Internal.hs:4140]: > Do the strict pairs go away? Do the inner pairs?

Yes, this is inlined so it goes away.

> Does GHC hang on to the fact that the keys are in WHNF?

This code is a little obsolete, I changed `(kx, x)` to `KeyValue kx x` so it should keep track of that. But since it's inlined I would expect it to do so anyway since the tuple will be gone and `Push` is strict in the key.

Comment (meooow25) [reply containers/src/Data/Map/Internal.hs:4140]: Here's the Core for

```hs
foo :: Map Int Int -> Map Int Int -> Ordering
foo = compare
```

On GHC 9.2.8 (decided to check a slightly older GHC)

<details>

```hs
Rec {
-- RHS size: {terms: 149, types: 164, coercions: 0, joins: 0/0}
$wgo13 [InlPrag=[2], Occ=LoopBreaker]
  :: Map Int Int -> Stack Int Int -> (# Ordering, Stack Int Int #)
[GblId, Arity=2, Str=<1L><1L>, Unf=OtherCon []]
$wgo13
  = \ (w_s6Ea :: Map Int Int) (w1_s6Eb :: Stack Int Int) ->
      case w_s6Ea of {
        Bin dt_a4XK k1_a4XL v2_a4XM ds1_a4XN ds2_a4XO ->
          case k1_a4XL of { I# x#_s6Wl ->
          case dt_a4XK of {
            __DEFAULT ->
              case $wgo13 ds1_a4XN w1_s6Eb of ww_s6Ee
              { (# ww1_s6U9, ww2_s6Ua #) ->
              case ww1_s6U9 of {
                __DEFAULT -> ww_s6Ee;
                EQ ->
                  case ww2_s6Ua of {
                    Push kx1_a4WQ x1_a4WR r_a4WS stk_a4WT ->
                      case kx1_a4WQ of { I# y#_s6Wo ->
                      case iterDown @Int @Int r_a4WS stk_a4WT of dt1_a4WV { __DEFAULT ->
                      case <# x#_s6Wl y#_s6Wo of {
                        __DEFAULT ->
                          case ==# x#_s6Wl y#_s6Wo of {
                            __DEFAULT -> (# GT, dt1_a4WV #);
                            1# ->
                              case v2_a4XM of { I# x#1_X1F ->
                              case x1_a4WR of { I# y#1_X1H ->
                              case <# x#1_X1F y#1_X1H of {
                                __DEFAULT ->
                                  case ==# x#1_X1F y#1_X1H of {
                                    __DEFAULT -> (# GT, dt1_a4WV #);
                                    1# -> $wgo13 ds2_a4XO dt1_a4WV
                                  };
                                1# -> (# LT, dt1_a4WV #)
                              }
                              }
                              }
                          };
                        1# -> (# LT, dt1_a4WV #)
                      }
                      }
                      };
                    Nada -> (# GT, Nada @Int @Int #)
                  }
              }
              };
            1# ->
              case w1_s6Eb of {
                Push kx1_a4WQ x1_a4WR r_a4WS stk_a4WT ->
                  case kx1_a4WQ of { I# y#_s6Wu ->
                  case iterDown @Int @Int r_a4WS stk_a4WT of dt1_a4WV { __DEFAULT ->
                  case <# x#_s6Wl y#_s6Wu of {
                    __DEFAULT ->
                      case ==# x#_s6Wl y#_s6Wu of {
                        __DEFAULT -> (# GT, dt1_a4WV #);
                        1# ->
                          case v2_a4XM of { I# x#1_X1F ->
                          case x1_a4WR of { I# y#1_X1H ->
                          case <# x#1_X1F y#1_X1H of {
                            __DEFAULT ->
                              case ==# x#1_X1F y#1_X1H of {
                                __DEFAULT -> (# GT, dt1_a4WV #);
                                1# -> (# EQ, dt1_a4WV #)
                              };
                            1# -> (# LT, dt1_a4WV #)
                          }
                          }
                          }
                      };
                    1# -> (# LT, dt1_a4WV #)
                  }
                  }
                  };
                Nada -> (# GT, Nada @Int @Int #)
              }
          }
          };
        Tip -> case w1_s6Eb of dt_a6ue { __DEFAULT -> (# EQ, dt_a6ue #) }
      }
end Rec }

-- RHS size: {terms: 10, types: 21, coercions: 0, joins: 0/0}
foo1 [InlPrag=[2]]
  :: Map Int Int
     -> Stack Int Int -> StrictPair Ordering (Stack Int Int)
[GblId,
 Arity=2,
 Str=<1L><1L>,
 Cpr=1,
 Unf=Unf{Src=InlineStable, TopLvl=True, Value=True, ConLike=True,
         WorkFree=True, Expandable=True,
         Guidance=ALWAYS_IF(arity=2,unsat_ok=True,boring_ok=False)
         Tmpl= \ (w_s6Ea [Occ=Once1] :: Map Int Int)
                 (w1_s6Eb [Occ=Once1] :: Stack Int Int) ->
                 case $wgo13 w_s6Ea w1_s6Eb of
                 { (# ww1_s6U9 [Occ=Once1], ww2_s6Ua [Occ=Once1] #) ->
                 :*: @Ordering @(Stack Int Int) ww1_s6U9 ww2_s6Ua
                 }}]
foo1
  = \ (w_s6Ea :: Map Int Int) (w1_s6Eb :: Stack Int Int) ->
      case $wgo13 w_s6Ea w1_s6Eb of { (# ww1_s6U9, ww2_s6Ua #) ->
      :*: @Ordering @(Stack Int Int) ww1_s6U9 ww2_s6Ua
      }

-- RHS size: {terms: 20, types: 33, coercions: 0, joins: 0/0}
foo :: Map Int Int -> Map Int Int -> Ordering
[GblId,
 Arity=2,
 Str=<1L><1L>,
 Unf=Unf{Src=InlineStable, TopLvl=True, Value=True, ConLike=True,
         WorkFree=True, Expandable=True,
         Guidance=ALWAYS_IF(arity=2,unsat_ok=True,boring_ok=False)
         Tmpl= \ (m1_a4Ws [Occ=Once1] :: Map Int Int)
                 (m2_a4Wt [Occ=Once1] :: Map Int Int) ->
                 case foo1 m1_a4Ws (iterDown @Int @Int m2_a4Wt (Nada @Int @Int)) of
                 { :*: o_a4Ya [Occ=Once1!] it_a4Yb [Occ=Once1!] ->
                 case o_a4Ya of {
                   LT -> LT;
                   EQ ->
                     case it_a4Yb of {
                       Push _ [Occ=Dead] _ [Occ=Dead] _ [Occ=Dead] _ [Occ=Dead] -> LT;
                       Nada -> EQ
                     };
                   GT -> GT
                 }
                 }}]
foo
  = \ (m1_a4Ws :: Map Int Int) (m2_a4Wt :: Map Int Int) ->
      case $wgo13 m1_a4Ws (iterDown @Int @Int m2_a4Wt (Nada @Int @Int))
      of
      { (# ww1_s6U9, ww2_s6Ua #) ->
      case ww1_s6U9 of wild1_a4Yd {
        __DEFAULT -> wild1_a4Yd;
        EQ ->
          case ww2_s6Ua of {
            Push ds_a5TP ds1_a5TQ ds2_a5TR ds3_a5TS -> LT;
            Nada -> EQ
          }
      }
      }
```

</details>

File: containers/src/Data/Map/Internal.hs [hunk 4]
```diff
@@ -4118,6 +4119,31 @@ deleteFindMax t = case maxViewWithKey t of
...
+  Iterator
+--------------------------------------------------------------------}
+
+-- See Note [Iterator] in Data.Set.Internal
+
+iterDown :: Map k a -> Stack k a -> Stack k a
+iterDown (Bin _ kx x l r) stk = iterDown l (Push kx x r stk)
+iterDown Tip stk = stk
+
+-- Create an iterator from a Map.
```
Comment (treeowl) [inline containers/src/Data/Map/Internal.hs:4132]:
```suggestion
-- Create an iterator from a Map, starting at the smallest key.
```

File: containers/src/Utils/Containers/Internal/EqOrdUtil.hs [hunk 5]
```diff
@@ -0,0 +1,38 @@
...
+  ( EqM(..)
+  , OrdM(..)
+  ) where
+
+#if !MIN_VERSION_base(4,11,0)
+import Data.Semigroup (Semigroup(..))
+#endif
+import Utils.Containers.Internal.StrictPair
+
+newtype EqM a = EqM { runEqM :: a -> StrictPair Bool a }
```
Comment (treeowl) [inline containers/src/Utils/Containers/Internal/EqOrdUtil.hs:12]: What is this?

File: containers/src/Data/Map/Internal.hs [hunk 6]
```diff
@@ -4284,41 +4310,69 @@ bin k x l r
...
+  {-# INLINE liftEq #-}
 
-instance (Ord k, Ord v) => Ord (Map k v) where
-    compare m1 m2 = compare (toAscList m1) (toAscList m2)
+-- | @since 0.5.9
+instance Eq2 Map where
+  liftEq2 keq eq m1 m2 = size m1 == size m2 && sameSizeLiftEq2 keq eq m1 m2
+  {-# INLINE liftEq2 #-}
+
+-- Assumes the maps are of equal size to skip the final check
```
Comment (treeowl) [inline containers/src/Data/Map/Internal.hs:4330]: Is this `EqM` business better than just using `foldr`? If so, why?

File: containers/src/Utils/Containers/Internal/EqOrdUtil.hs (hunk 5 above)
Comment (meooow25) [reply containers/src/Utils/Containers/Internal/EqOrdUtil.hs:12]: This exists for its semigroup instance.

As documented, it composes the functions and short-circuits on false. This is used in the Eq implementations where false means a pair of unequal elements were found, and due to short-circuiting it skips further comparisons.

Comment (treeowl) [reply containers/src/Utils/Containers/Internal/EqOrdUtil.hs:12]: I still don't get the point. Why not just `foldrWithKey` over the `Map`, passing the `Stack` along?

File: containers/src/Data/Map/Internal.hs (hunk 6 above)
Comment (meooow25) [reply containers/src/Data/Map/Internal.hs:4330]: Yes it is, you can see a `foldr` version in #1016 (named `setCmp`).

To expand it out, `foldMap` with `EqM` becomes something like

```hs
                              -- v result of comparing the map and the iterator
go :: Map k a -> Stack k a -> (# Ordering, Stack k a #)
                                        -- ^ remaining iterator
```
We do this recursively and short-circuit on EQ.

In contrast, `foldr` becomes something like this, which is more of a continuation style

```hs
                                                      -- v final result
go :: Map k a -> Stack k a -> (Stack k a -> Ordering) -> Ordering
                             -- ^ if not EQ, call this with remaining iterator
```

Which is slower.

File: containers/src/Utils/Containers/Internal/EqOrdUtil.hs (hunk 5 above)
Comment (meooow25) [reply containers/src/Utils/Containers/Internal/EqOrdUtil.hs:12]: Ah yes, that turns out to be slower. Just replied with it in the comment below.

File: containers/src/Data/Map/Internal.hs (hunk 6 above)
Comment (treeowl) [reply containers/src/Data/Map/Internal.hs:4330]: All right, the slowness of the `foldr` should be documented if it isn't already. Do you know why it's slower? Is there a problem inlining `foldr` properly? Or an issue with arity analysis (does `oneShot` make a difference)?

Comment (meooow25) [reply containers/src/Data/Map/Internal.hs:4330]: `oneShot` does improve things but it's still slower. Arity analysis is also working (I didn't try switching it off but it can only be worse).  
I'm not surprised that it is slower though. Not an expert here, but it has to heap allocate those continuation closures which is surely expensive. No allocations required in the foldMap version.

Comment (treeowl) [reply containers/src/Data/Map/Internal.hs:4330]: Hmm? Why do we need to heap-allocate continuation closures when arity analysis is working? Isn't the state all in the `Stack`? I admit I'm not fully alert right now (I was kept up much of the night by intermittent screaming ☹️), so I could be missing something obvious.

Comment (meooow25) [reply containers/src/Data/Map/Internal.hs:4330]: So we have in `Set.foldr`

```hs
go :: b -> Set a -> b
go z' (Bin _ x l r) = go (f x (go z' r)) l
```

`b` is `Stack a -> Ordering`, so

```hs
go :: (Stack a -> Ordering) -> Set a -> Stack a -> Ordering
go z' (Bin _ x l r) = go (f x (go z' r)) l
```

When arity analysis decides to eta-expand, we get

```hs
go :: (Stack a -> Ordering) -> Set a -> Stack a -> Ordering
go z' (Bin _ x l r) eta = go (f x (go z' r)) l eta
```

This has helped avoid creating and returning a closure, but there is still a closure as input.  
I don't know whether some transformation can get rid of that, if it's even possible.

---

This doesn't happen for something like `[]`, where `foldr` is

```hs
go :: [a] -> b
go (x : xs) = f x (go xs)
```

since there is no input `b` which sticks around.

Comment (treeowl) [reply containers/src/Data/Map/Internal.hs:4330]: Ah, okay. I think I get that now.

**Comment by meooow25** [comment]
Thanks for reviewing!
